[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xf78c6c"
index = 16

[[colors.indexed_colors]]
color = "0xff5370"
index = 17

[[colors.indexed_colors]]
color = "0x444267"
index = 18

[[colors.indexed_colors]]
color = "0x32374d"
index = 19

[[colors.indexed_colors]]
color = "0x8796b0"
index = 20

[[colors.indexed_colors]]
color = "0x959dcb"
index = 21

[colors.bright]
black = "0x676e95"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0xffffff"
yellow = "0xffcb6b"

[colors.cursor]
cursor = "0x959dcb"
text = "0x292d3e"

[colors.normal]
black = "0x292d3e"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0x959dcb"
yellow = "0xffcb6b"

[colors.primary]
background = "0x292d3e"
foreground = "0x959dcb"

[cursor]
style = "Beam"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "None"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "º"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "¡"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "¢"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "∞"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "§"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "¶"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "•"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "ª"
key = "Key9"
mods = "Alt"

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Maximized"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 10
y = 10
